export const SET_FETCHING = 'SET_FETCHING';
export const SET_NODES = 'SET_NODES';
export const SET_GROUPS_NODES = 'SET_GROUPS_NODES';
export const SET_GROUPS = 'SET_GROUPS';
export const SET_ACTIVE_NODES = 'SET_ACTIVE_NODES';
export const SELECTION_TOGGLE_NODE = 'SELECTION_TOGGLE_NODE';
export const SELECT_ALL_NODES = 'SELECT_ALL_NODES';
export const CANCEL_SELECTION_MODE = 'CANCEL_SELECTION_MODE';
export const INCREASE_NODE_COUNT = 'INCREASE_NODE_COUNT';
export const ADD_NODE = 'ADD_NODE';
export const EDIT_NODE_MODE = 'EDIT_NODE_MODE';
export const RENAME_NODE = 'RENAME_NODE';
export const DELETE_NODE = 'DELETE_NODE';
export const SET_MENU_MODE = 'SET_MENU_MODE';

export const SET_VIEW_FETCHING = 'SET_VIEW_FETCHING';
export const SET_VIEW_DATA = 'SET_VIEW_DATA';
export const UPDATE_NODE = 'UPDATE_NODE';
export const ATTACH_EXPRESSION = 'ATTACH_EXPRESSION';
export const DETACH_EXPRESSION = 'DETACH_EXPRESSION';
export const ATTACH_TRANSLATION = 'ATTACH_TRANSLATION';
export const DETACH_TRANSLATION = 'DETACH_TRANSLATION';

export const ATTACH_EXPRESSION_TRANSCRIPTION = 'ATTACH_EXPRESSION_TRANSCRIPTION';
export const ATTACH_TRANSLATION_TRANSCRIPTION = 'ATTACH_TRANSLATION_TRANSCRIPTION';
export const DETACH_TRANSLATION_TRANSCRIPTION = 'DETACH_TRANSLATION_TRANSCRIPTION';
export const SHOW_TRANSLATION_TRANSCRIPTIONS = 'SHOW_TRANSLATION_TRANSCRIPTIONS';

export const SET_SUBROW_OBJECT_ID = 'SET_SUBROW_OBJECT_ID';

/* STATE CONSTANTS */

export const MENU_MODE_DEFAULT = 0;
export const MENU_MODE_SELECT = 1;

export const NODE_FOLDER = 0;
export const NODE_SLICE = 1;

export const VISIBILITY_PRIVATE = 0;
export const VISIBILITY_PUBLIC = 1;

export const EXERCISE_DIRECT = 0;
export const EXERCISE_REVERSE = 1;
export const EXERCISE_CYCLES = 2;
export const EXERCISE_LISTEN = 3;