export const SET_FETCHING = 'SET_FETCHING';
export const SET_NODES = 'SET_NODES';
export const SET_GROUPS_NODES = 'SET_GROUPS_NODES';
export const SET_GROUPS = 'SET_GROUPS';
export const INCREASE_NODE_COUNT = 'INCREASE_NODE_COUNT';

export const SET_VIEW_FETCHING = 'SET_VIEW_FETCHING';
export const SET_VIEW_DATA = 'SET_VIEW_DATA';
export const UPDATE_NODE = 'UPDATE_NODE';
export const ATTACH_EXPRESSION = 'ATTACH_EXPRESSION';
export const DETACH_EXPRESSION = 'DETACH_EXPRESSION';
export const ATTACH_TRANSLATION = 'ATTACH_TRANSLATION';
export const DETACH_TRANSLATION = 'DETACH_TRANSLATION';

export const NODE_FOLDER = 0;
export const NODE_SLICE = 1;

export const VISIBILITY_PRIVATE = 0;
export const VISIBILITY_PUBLIC = 1;